# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FQ_01' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FQ_01

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  target 'FQ_01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

target 'FQ_01-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FQ_01-tvOS

  target 'FQ_01-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
