export enum UserActionsEnum {
    AUTH = 'AUTH',
    SIGNUP_ERROR_PASSWORD_REPEAT = 'SIGNUP_ERROR_PASSWORD_REPEAT',
    SAVE_USER_PHOTO = 'SAVE_USER_PHOTO',
    SET_USERNAME = 'SET_USERNAME',
    SET_PASSWORD = 'SET_PASSWORD',
}